---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: auth-frontend
spec:
  replicas: 2
  strategy:
   type: RollingUpdate
   rollingUpdate:
    maxUnavailable: 50%
    maxSurge: 50%
  template:
    metadata:
      labels:
        app: invoice-auth
        tier: frontend
        track: stable
    spec:
      containers:
      - name: auth-frontend
        image: BUILD_TAG
        resources:
         requests:
          cpu: 100m
          memory: 100Mi
        ports:
        - containerPort: 3000
        imagePullPolicy: IfNotPresent
