---
apiVersion: v1
kind: Service
metadata:
  name: auth-frontend
  labels:
    app: invoice-auth
    tier: frontend
    track: stable
spec:
  type: NodePort
  selector:
    app: invoice-auth
    tier: frontend
    track: stable
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30009
